[versions]

junit = "6.0.1"
mockito = "5.21.0"
enonicDefaults = "2.1.6"
enonicXpGradle = "4.0.0-A2"

[libraries]

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mockito-core = { module = "org.mockito:mockito-bom", version.ref = "mockito" }
mockito-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }

[plugins]
enonic-defaults = { id = "com.enonic.defaults", version.ref = "enonicDefaults" }
enonic-xp-base = { id = "com.enonic.xp.base", version.ref = "enonicXpGradle" }
